### ISSUE TITLE
Error: Duster not found

### ISSUE THREAD

**Issue by attac-t** [tighten/duster-action#3]
<img width="1204" alt="image" src="https://github.com/tighten/duster-action/assets/73131281/08ce8c34-005a-4eba-a28d-f2e52b492fcf">

**Comment by driftingly** [comment]
Just ran into this same issue on TLint.  I'll let you know when I figure out what’s going on.

**Comment by driftingly** [comment]
@attac-t This should be fixed now.  Thanks @tonysm 🙌

**Comment by attac-t** [comment]
> @attac-t This should be fixed now.  Thanks @tonysm 🙌 
> 

Fix confirmed. Cheers!
