### ISSUE TITLE
Bug Report: Duplicate declaration of static variable $model 

### ISSUE THREAD

**Issue by Ediezzle** [tighten/duster-action#7]
Running the linter on my local dev environment works but when the workflow runs on Github it always fails with the error attached in the screenshot. I don't know where the reported file is coming from as it doesn't exist in my codebase.
<img width="1044" alt="Screenshot 2023-11-28 at 20 08 25" src="https://github.com/tighten/duster-action/assets/52998785/a62300a4-d0a1-4fdf-a618-384da6488422">

**Comment by Bottelet** [comment]
Yeah same, just came to report this problem as well, just started experiencing the problem yesterday, and had no problem until then.

**Comment by Bottelet** [comment]
I believe this is the issue:

Duster depends on composer:latest:
[Link to duster action Dockerfile](https://github.com/tighten/duster-action/blob/2.x/Dockerfile#L1C6-L1C21)

composer:latest uses php:8-alpine:
[Link to composer latest Dockerfile](https://github.com/tighten/duster-action/blob/2.x/Dockerfile#L1C6-L1C21)

However, php:8-alpine now corresponds to PHP 8.3, and Duster is not compatible with PHP 8.3.

**Comment by Ediezzle** [comment]
Noted with thanks. I also found out that there is already an open issue about this on the duster's repo: https://github.com/tighten/duster/issues/134
