### ISSUE TITLE
Duplicate declaration of static variable $model

### ISSUE THREAD

**Issue by olivsinz** [tighten/duster-action#8]
Hello everyone!

I wanted to express my sincere gratitude for your efforts in developing and maintaining Tlint, Duster and Duster-Action. Your dedication to these projects has been invaluable to the community, and it has undoubtedly made a positive impact on many developers, including myself.

I've been using Duster for months now, and it has significantly enhanced my workflows. Your commitment to delivering a high-quality and reliable tool is truly commendable.

While working with the package, I encountered a situation that I believe may be an issue, and I would like to bring it to your attention. I understand that maintaining an open-source project involves a lot of hard work, and I appreciate the time and energy you invest in addressing issues and improving the package.

Thank you once again for your outstanding contribution to the community. I look forward to your guidance and assistance in resolving the matter I've encountered.

Here's a screenshot for more details.

![Screenshot 2023-11-30 at 16-25-50 Duster   Tlint · ValerioBurgarello_facilegestion@73b6e30](https://github.com/tighten/duster-action/assets/29924640/7cdfd836-1f4f-4794-aba7-16c022681727)

https://github.com/tighten/tlint/blob/4d126aa19b6acbeb3a4884fa28ff25ff230f8bb1/src/Linters/NoDatesPropertyOnModels.php#L20

**Comment by GussRw** [comment]
Hi @olivsinz 
You could use my duster-action fork while the duster team fix it  `uses: gussrw/duster-action@v2.0.2`
There is already an open issue about this: https://github.com/tighten/duster/issues/134

**Comment by driftingly** [comment]
Thanks for reporting @olivsinz and helping out with your fork 🙏 
This has been fixed in [Duster 2.6.0](https://github.com/tighten/duster/releases/tag/v2.6.0)

**Comment by olivsinz** [comment]
> Hi @olivsinz You could use my duster-action fork while the duster team fix it `uses: gussrw/duster-action@v2.0.2` There is already an open issue about this: [tighten/duster#134](https://github.com/tighten/duster/issues/134)

Hi @GussRw thanks a lot.

**Comment by olivsinz** [comment]
> Thanks for reporting @olivsinz and helping out with your fork 🙏 This has been fixed in [Duster 2.6.0](https://github.com/tighten/duster/releases/tag/v2.6.0)

Hi @driftingly You're welcome. thanks to you.

**Comment by driftingly** [comment]
Whoops, thanks to @GussRw for the fork! 😅
